# Generated by Django 4.0.5 on 2022-07-09 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'candidacy',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('date_and_time', models.DateTimeField()),
                ('location', models.TextField()),
                ('max_participants', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='CandidacyCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player', models.BooleanField(default=False)),
                ('speaker', models.BooleanField(default=False)),
                ('arbiter', models.BooleanField(default=False)),
                ('candidacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_candidacies', to='events.candidacy')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_candidacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidacy_candidate',
            },
        ),
        migrations.AddField(
            model_name='candidacy',
            name='candidates',
            field=models.ManyToManyField(related_name='candidacies', through='events.CandidacyCandidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='events.event'),
        ),
    ]
