# Generated by Django 4.0.5 on 2022-07-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacycandidate',
            name='disk_jockey',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidacycandidate',
            name='candidacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_candidates', to='events.candidacy'),
        ),
    ]
