# Generated by Django 4.0.5 on 2022-07-09 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_candidacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='candidates',
            field=models.ManyToManyField(related_name='candidacies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidacy',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='events.event'),
        ),
    ]
