name: Build and test

on: [pull_request]
env:
  LUDIGESTION_SECRET_KEY: x^7pz2d(06mt_mi%$_kjf@+3xcg--v&ufcmv_n-ax7awmv0f3
  LUDIGESTION_DEBUG: False

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      run: pip install poetry
    - name: Install app
      run: make setup
    - name: Run tests
      run: make test
